version: "3.9"
services:
    primes:
        build: .
        command: primes
        container_name: prime_sieve
        environment:
            - NUM_PRIMES=10000
            - STARTING_PRIME_INDEX=1
            - SOCKET_LOCATION=/var/run/primes/prime_sieve.sock
        volumes:
            - prime_sieve_socket:/var/run/primes:rw

    guesser1:
        build: .
        command: guesser
        container_name: guesser1
        depends_on:
            - primes
        environment:
            - EMAIL=Q3PaVAn9je@gmail.com
            - USERNAME=Q3PaVAn9je
            - PASSWORD=password
        volumes:
            - prime_sieve_socket:/var/run/primes:rw

volumes:
    prime_sieve_socket:
